### ISSUE TITLE
MusicBot 의 블로그에서 번역하기

### ISSUE THREAD

**Issue by jljl73** [18-1-SKKU-OSS/2018-1-OSS-E4#3]
Command 부분이 실제 musicbot에서 이용시 필요한 부분이므로
Command 부분을 먼저 번역하기로 하죠

**Comment by palabear** [comment]
Command 부분 번역하였습니다

**Comment by jljl73** [comment]
Command 해석하신 것에서 참고로

명령어 앞에 !가 고정되어 있는건 아니고 Default로 설정되어 있는거고, 원한다면 바꿀수 있어요
