### ISSUE TITLE
About redirect URIs

### ISSUE THREAD

**Issue by palabear** [18-1-SKKU-OSS/2018-1-OSS-E4#7]
Bot을 추가하려 할때 Redirect URI를 입력해야하는데 이 redirect URI에 대한 설명이 부족한 것 같습니다. 
jljl73님 이에 대한 설명을 해주시면 감사하겠습니다.

**Comment by jljl73** [comment]
수정했는데 말씀하신부분이 맞는지 확인해주시고 괜찮은지도 좀 확인해주세요
